CREATE TABLE "BOOKMARK" (
  	"ID" INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY ( START WITH 1 INCREMENT BY 1 MINVALUE 1 MAXVALUE 
							    2147483647 NO CYCLE CACHE 20 NO ORDER ), 
		"USERID" VARCHAR(50) NOT NULL DEFAULT '', 
		"TITLE" VARCHAR(100) NOT NULL DEFAULT '', 
		"LINK" VARCHAR(500)
	)
	 
CREATE TABLE "DEPARTMENT" (
		"DEPTID" INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY ( START WITH 1 INCREMENT BY 1 MINVALUE 1 MAXVALUE 
							    2147483647 NO CYCLE CACHE 20 NO ORDER ), 
		"DEPTNAME" VARCHAR(100) NOT NULL DEFAULT '', 
		"SHORTNAME" VARCHAR(10) NOT NULL DEFAULT '', 
		"DESCRIPTION" LONG VARCHAR, 
		"USERID" VARCHAR(50) NOT NULL DEFAULT ''
	)
	 
CREATE TABLE "LOGIN" (
		"USERID" VARCHAR(100) NOT NULL, 
		"PASSWORD" VARCHAR(50) NOT NULL DEFAULT '', 
		"ROLE" VARCHAR(20) NOT NULL DEFAULT '', 
		"LASTLOGIN" TIMESTAMP
	)
	 
CREATE TABLE "NOTIFICATION" (
		"ID" INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY ( START WITH 1 INCREMENT BY 1 MINVALUE 1 MAXVALUE 
							    2147483647 NO CYCLE CACHE 20 NO ORDER ), 
		"USERID" VARCHAR(100), 
		"CATEGORY" VARCHAR(50), 
		"CATEGORYID" INTEGER, 
		"TIMEUPDATE" TIMESTAMP
	)
	 
CREATE TABLE "POLICY" (
		"POLICYID" INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY ( START WITH 1 INCREMENT BY 1 MINVALUE 1 MAXVALUE 
							    2147483647 NO CYCLE CACHE 20 NO ORDER ), 
		"TITLE" VARCHAR(100) NOT NULL DEFAULT '', 
		"DESCRIPTION" LONG VARCHAR, 
		"AMOUNTPERCENT" SMALLINT NOT NULL DEFAULT 100, 
		"AVAILABLE" SMALLINT NOT NULL DEFAULT 1
	)
	 
CREATE TABLE "REPORT" (
		"REPORTID" INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY ( START WITH 1 INCREMENT BY 1 MINVALUE 1 MAXVALUE 
							    2147483647 NO CYCLE CACHE 20 NO ORDER ), 
		"TITLE" VARCHAR(100) NOT NULL DEFAULT '', 
		"DESCRIPTION" LONG VARCHAR, 
		"TYPE" VARCHAR(20) NOT NULL DEFAULT '', 
		"DATE" DATE NOT NULL DEFAULT CURRENT DATE, 
		"USERID" VARCHAR(50) NOT NULL DEFAULT '', 
		"FILE" BLOB(1000) INLINE LENGTH 68 NOT NULL DEFAULT "SYSIBM"."BLOB"('')
	)
	 
CREATE TABLE "USER" (
		"USERID" VARCHAR(100) NOT NULL, 
		"SOCIALSECURITY" VARCHAR(100), 
		"FIRSTNAME" VARCHAR(100), 
		"MIDDLENAME" VARCHAR(100), 
		"LASTNAME" VARCHAR(100), 
		"GENDER" VARCHAR(10),
		"DEPTID" INTEGER, 
		"DESIGNATION" VARCHAR(50), 
		"ADDRESS" VARCHAR(500), 
		"PHONE" VARCHAR(20), 
		"MOBILE" VARCHAR(20), 
		"EMAIL" VARCHAR(100), 
		"PHOTO" BLOB(1000) INLINE LENGTH 68, 
		"DOB" DATE
	)
	 
CREATE TABLE "VOUCHER" (
		"VOUCHERID" INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY ( START WITH 1 INCREMENT BY 1 MINVALUE 1 MAXVALUE 
							    2147483647 NO CYCLE CACHE 20 NO ORDER ), 
		"USERID" VARCHAR(50) NOT NULL DEFAULT '0', 
		"TITLE" VARCHAR(100) NOT NULL DEFAULT '', 
		"AMOUNT" DOUBLE NOT NULL DEFAULT 0.0, 
		"VTYPEID" INTEGER NOT NULL DEFAULT 0, 
		"DATE" DATE NOT NULL DEFAULT CURRENT DATE, 
		"DESCRIPTION" LONG VARCHAR DEFAULT NULL, 
		"ATTACHMENT" BLOB(1000) INLINE LENGTH 68, 
		"REJECTREASON" LONG VARCHAR, 
		"POLICYID" INTEGER NOT NULL DEFAULT 0
	)
	 
	DISTRIBUTE BY HASH ("VOUCHERID")
	
CREATE TABLE "VOUCHERTYPE_DEPT" (
		"ID" INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY ( START WITH 1 INCREMENT BY 1 MINVALUE 1 MAXVALUE 
							    2147483647 NO CYCLE CACHE 20 NO ORDER ), 
		"VTYPEID" VARCHAR(10), 
		"DEPTID" VARCHAR(10)
	)
	 
CREATE TABLE "VOUCHERTYPE_POLICY" (
		"ID" INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY ( START WITH 1 INCREMENT BY 1 MINVALUE 1 MAXVALUE 
							    2147483647 NO CYCLE CACHE 20 NO ORDER ), 
		"VTYPEID" INTEGER NOT NULL, 
		"POLICYID" INTEGER NOT NULL
	)
	 
CREATE TABLE "VOUCHER_STATUS" (
		"STATUSID" INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY ( START WITH 1 INCREMENT BY 1 MINVALUE 1 MAXVALUE 
							    2147483647 NO CYCLE CACHE 20 NO ORDER ), 
		"VOUCHERID" INTEGER, 
		"STATUS" VARCHAR(15), 
		"USERID" VARCHAR(50), 
		"TIME" TIME
	)
	 
CREATE TABLE "VOUCHER_TYPE" (
		"VTYPEID" INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY ( START WITH 1 INCREMENT BY 1 MINVALUE 1 MAXVALUE 
							    2147483647 NO CYCLE CACHE 20 NO ORDER ), 
		"TITLE" VARCHAR(100) NOT NULL DEFAULT '', 
		"DESCRIPTION" LONG VARCHAR
	)


------------------- TRIGGERS, INDEX & CONSTRAINTS Statements --------------

ALTER TABLE "BOOKMARK" ADD CONSTRAINT "BOOKMARK_PK" PRIMARY KEY
	("ID");

ALTER TABLE "DEPARTMENT" ADD CONSTRAINT "department_PK" PRIMARY KEY
	("DEPTID");

ALTER TABLE "LOGIN" ADD CONSTRAINT "LOGIN_PK" PRIMARY KEY
	("USERID");

ALTER TABLE "NOTIFICATION" ADD CONSTRAINT "notification_PK" PRIMARY KEY
	("ID");

ALTER TABLE "POLICY" ADD CONSTRAINT "POLICY_PK" PRIMARY KEY
	("POLICYID");

ALTER TABLE "REPORT" ADD CONSTRAINT "REPORT_PK" PRIMARY KEY
	("REPORTID");

ALTER TABLE "USER" ADD CONSTRAINT "user_PK" PRIMARY KEY
	("USERID");

ALTER TABLE "VOUCHER" ADD CONSTRAINT "voucher_PK" PRIMARY KEY
	("VOUCHERID");

ALTER TABLE "VOUCHERTYPE_DEPT" ADD CONSTRAINT "VOUCHERTYPE_DEPT_PK" PRIMARY KEY
	("ID");

ALTER TABLE "VOUCHERTYPE_POLICY" ADD CONSTRAINT "VOUCHERTYPE_POLICY_PK" PRIMARY KEY
	("ID");

ALTER TABLE "VOUCHER_STATUS" ADD CONSTRAINT "status_PK" PRIMARY KEY
	("STATUSID");

ALTER TABLE "VOUCHER_TYPE" ADD CONSTRAINT "VOUCHER_TYPE_PK" PRIMARY KEY
	("VTYPEID");
